public class MathClass {
    public Integer addition(integer num1, integer num2) {
        Integer sum = num1 + num2;
        return sum;
        
    }
    public Integer subtraction(integer num1, integer num2) {
        Integer sub = num1 - num2;
        return sub;
        
    }

    public Integer multiplication(integer num1, integer num2) {
        Integer mul = num1 * num2;
        return mul;
        
    }

    public Integer division(integer num1, integer num2) {
        Integer div = num1 / num2;
        return div;
        
    }


}
