public class studentInfo {
    public static void studentInfo(){
        System.debug('Welcome to my Class');
    }


    public static void studentNames() {
        list<string> listofStudents = new list<string>();
        listofStudents.add('Tomas');
        listofStudents.add('Moon');
        listofStudents.add('Toon');
        listofStudents.add('Soon');
        system.debug('My Students are ' + listofStudents);

    }
}
